spring:
  application:
    name: todo-app

  # デフォルトプロファイルをdevに設定
  profiles:
    active: dev

  # Thymeleaf設定（共通）
  thymeleaf:
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html

# サーバー設定（共通）
server:
  port: 8090
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# Actuator configuration for health checks
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
  info:
    env:
      enabled: true

# アプリケーション固有設定（共通）
app:
  name: "ToDo Application"
  version: "1.0.0"
  description: "Spring Boot ToDo Application with Material Design"
  pagination:
    default-page-size: 10
    max-page-size: 100
